version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  ml:
    build:
      context: ./ML
      dockerfile: Dockerfile
    ports:
      - "5001:5000"